apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    app: apache #act as a tag
spec:
  replicas: 2 #t2 micro
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache-container
        image: sergebouopda/serge_apache_image:v1.0.1
        ports:
        - containerPort: 80